### PR TITLE
Player / Shop / Sound Effects

### PR DESCRIPTION
**Pull request by ultimate1112**
Merge for Safehouse, Items and Player Sound Effects. Major additions include 3 new weapons that act as upgrades to base weapons, new safehouse interior, new shopkeeper NPC, new sound effects for the player and a torch item that creates a light source for the player.

## **Feature #125** 
- Added shopkeeper assets. Now is an actual NPC character and has a portrait in the shop UI menu.
- Added safehouse assets (Not final but close to it)

## **Feature #139**
As a result of user testing, devised new weapons and balanced accordingly.
- Removed Dual Dagger, Great Axe and Katana (user testing, not relevant to post-apocalyptic setting)
- Added Machete, Sledgehammer and Baseball Bat (stats not final)
- Added torch item with assets and animations
- Created new renderer to render assets after lighting system. This means you can have add assets that are unaffected by the lighting system.

## **Feature #137**
Added some sound effects to:
- Player getting critically hurt (when the player gets wounded)
- Bandage use
- Player picking up various armor / weapon items

## **Bug Fixes**
- Fixed some player movement bugs
- Fixed lighting issue with UI through the new renderer

### CODE REVIEW

**Comment by DancingBrian** [comment]
The pull request currently says that it's a draft version. Would you like us to test it now or when the pull request is finished?

**Comment by DancingBrian** [comment]
Love the new safehouse design! Here were a couple of things that came up while testing:
* Wasn't able to test the new weapons as purchasing them didn't change the sword to the new weapon. For example if I bought the baseball bat at the safehouse then leaving the safehouse reverted back to the sword. The visuals of the new weapons look good though.
* I like the idea of the torch, looks cool! A very minor thing: when sprinting, the torch doesn't keep up with the animation (i.e. it lags behind the player).
* Love the heartbeat sound, especially how it looks when the player dies (the torch going out and the pause). I feel that the healing sound was a little too loud and sounded a little like a magic spell rather than applying a bandaid/bandage.
* Wasn't sure how to test the picking up armor/weapons sound, where abouts in the game can I pick up armor to test it?
* When purchasing the armor from the shop the player gets the helmet as well (without needing to buy it), is this intended?
* One of the bullets on level 2 turns into a black square (see screenshot below). This black square also appears on level 3.
* If entering the safehouse on 1 wound level, the next level displays that you have full health but you only have 1 wound level left (one hit will kill you).

image

**Comment by Bluehalomango** [comment]
> * Wasn't able to test the new weapons as purchasing them didn't change the sword to the new weapon. For example if I bought the baseball bat at the safehouse then leaving the safehouse reverted back to the sword. The visuals of the new weapons look good though.
> * If entering the safehouse on 1 wound level, the next level displays that you have full health but you only have 1 wound level left (one hit will kill you).

These have been fixed.

> * I like the idea of the torch, looks cool! A very minor thing: when sprinting, the torch doesn't keep up with the animation (i.e. it lags behind the player).

Not sure what we can do about this at the moment, it just has to do with the fact that the torch is a separate animation from the player. We'll have a look into it but this might be something for polishing.

> * Wasn't sure how to test the picking up armor/weapons sound, where abouts in the game can I pick up armor to test it?

You can no longer pickup weapons and armour ingame so we might change the sound effect to ammo, coins, etc.

> * One of the bullets on level 2 turns into a black square (see screenshot below). This black square also appears on level 3.

Not sure why that would happen, we haven't really touched the bullet this sprint. Might be something that changed in Team 5's changes to level or it could be something else. We had issues with this happening with the torch but we thought we solved that so maybe this has to do with the torch instead. Will require more testing I suspect.

> * When purchasing the armor from the shop the player gets the helmet as well (without needing to buy it), is this intended?

This is partially intended (more a side effect of how we calculate damage values and store player state). The idea was to increase the price of the full armour set to balance it (as it is a rather large buff) but we might look at changing how its implemented in our next pull request later this week.

**Comment by DancingBrian** [comment]
> 
> 
> > * Wasn't able to test the new weapons as purchasing them didn't change the sword to the new weapon. For example if I bought the baseball bat at the safehouse then leaving the safehouse reverted back to the sword. The visuals of the new weapons look good though.
> > * If entering the safehouse on 1 wound level, the next level displays that you have full health but you only have 1 wound level left (one hit will kill you).
> 
> These have been fixed.
> 
> > * I like the idea of the torch, looks cool! A very minor thing: when sprinting, the torch doesn't keep up with the animation (i.e. it lags behind the player).
> 
> Not sure what we can do about this at the moment, it just has to do with the fact that the torch is a separate animation from the player. We'll have a look into it but this might be something for polishing.
> 
> > * Wasn't sure how to test the picking up armor/weapons sound, where abouts in the game can I pick up armor to test it?
> 
> You can no longer pickup weapons and armour ingame so we might change the sound effect to ammo, coins, etc.
> 
> > * One of the bullets on level 2 turns into a black square (see screenshot below). This black square also appears on level 3.
> 
> Not sure why that would happen, we haven't really touched the bullet this sprint. Might be something that changed in Team 5's changes to level or it could be something else. We had issues with this happening with the torch but we thought we solved that so maybe this has to do with the torch instead. Will require more testing I suspect.
> 
> > * When purchasing the armor from the shop the player gets the helmet as well (without needing to buy it), is this intended?
> 
> This is partially intended (more a side effect of how we calculate damage values and store player state). The idea was to increase the price of the full armour set to balance it (as it is a rather large buff) but we might look at changing how its implemented in our next pull request later this week.

Ah nice, yep was able to test new weapons now. The weapons seem to be working well on my end. Very minor note is that the long attack durations still seem to apply their damage instantly when pressing space (rather than having to wait for the attack duration), so you could attack then run which cancels the animation but still applies the damage.

Did receive a crash when leaving level 3, screenshot below. Other than that everything looks good!

image

**Review by DancingBrian — APPROVED** [review]

**Comment by Bluehalomango** [comment]
> Ah nice, yep was able to test new weapons now. The weapons seem to be working well on my end. Very minor note is that the long attack durations still seem to apply their damage instantly when pressing space (rather than having to wait for the attack duration), so you could attack then run away, which would cancel the attack animation but still apply the damage.

I see that as more of a strategy to playing the game than a bug at the moment. At least while the enemies are as tough as they are but maybe it'll change later.

> Did receive a crash when leaving level 3, screenshot below. Other than that everything looks good!

Thanks for catching that, wasn't actually aware there was a level after level 3 in-game yet. I've gone and (hopefully) added all the assets needed into level 4.

**Pull request merged**
