### PR TITLE
S3 T2 Checkpoint + Carry State + Safehouse Store

### PR DESCRIPTION
**Pull request by Bluehalomango**
New pull request to add in major safehouse and saving features. 

- The player's state can now carry over between levels and their state is saved when they enter a safehouse so when they die next, they can respawn back at the safehouse in their previous state. 

- There is now also a safehouse store (also located next to level spawn for testing purposes) that players can interact with and successfully buy items off. All appearances and designs are still works in progress and we plan on conducting user testing to help finalise the design of the shop menu.

### CODE REVIEW

**Comment by DancingBrian** [comment]
Nice, it's looking good! I like the way you have implemented the shop interface, and reload checkpoint seems to work really well. There were a couple of issues I ran into while playing (some are really nit-picking though so feel free to ignore):

- When starting level 3, the shop interface automatically appears
- The shop feedback text ("Purchased item", "Already equipped", etc) remains displayed between shop keepers
- For some reason the safehouse music now plays over epilogue scene after exiting the level 3 safehouse.
- When picking up a pile of coins, occasionally this adds 0 new coins.
- If the player has an axe or dagger equipped, then the shop allows you to buy another one of the same weapon, and won't let you buy the sword (as it says it is already equipped). Also there is a related issues where each start of level swaps you back to the sword.
- When entering the safehouse all rocks get reloaded, however the number of rocks doesn't decrease. For example if I enter the safehouse with 10 rocks in my inventory + 2 rocks ready to throw, then inside the safehouse it will "reload" automatically and therefore will have 10 rocks in my inventory + 5 rocks ready to throw (essentially gaining 3 rocks)
- It would be awesome if when buying items in the shop that it updates the sprite on the right side of the shop interface (seems like this feature might already be coming in the future though).
- I know you haven't finalised design, but it would be nice to have some sort of box around the currently selected item in the store so the user can clearly see which one is selected.

Super minor things:
- Dash text description is currently hard to understand, possibly the word "everything" is not meant to be there.
- Bandaid text seems to suggest that you can regenerate your health, which is partially true but it's not possible to regenerate wound levels. It might be more clear saying something like "you may regenerate small injuries but not wound levels".
- Currently sounds like the invincibility is a permanent effect. Might be helpful to list the effects duration (5 seconds, for the current level, etc).

**Comment by 25Ericcheong** [comment]
> Nice, it's looking good! I like the way you have implemented the shop interface, and reload checkpoint seems to work really well. There were a couple of issues I ran into while playing (some are really nit-picking though so feel free to ignore):
> 
> * When starting level 3, the shop interface automatically appears
> * The shop feedback text ("Purchased item", "Already equipped", etc) remains displayed between shop keepers
> * For some reason the safehouse music now plays over epilogue scene after exiting the level 3 safehouse.
> * When picking up a pile of coins, occasionally this adds 0 new coins.
> * If the player has an axe or dagger equipped, then the shop allows you to buy another one of the same weapon, and won't let you buy the sword (as it says it is already equipped). Also there is a related issues where each start of level swaps you back to the sword.
> * When entering the safehouse all rocks get reloaded, however the number of rocks doesn't decrease. For example if I enter the safehouse with 10 rocks in my inventory + 2 rocks ready to throw, then inside the safehouse it will "reload" automatically and therefore will have 10 rocks in my inventory + 5 rocks ready to throw (essentially gaining 3 rocks)
> * It would be awesome if when buying items in the shop that it updates the sprite on the right side of the shop interface (seems like this feature might already be coming in the future though).
> * I know you haven't finalised design, but it would be nice to have some sort of box around the currently selected item in the store so the user can clearly see which one is selected.
> 
> Super minor things:
> 
> * Dash text description is currently hard to understand, possibly the word "everything" is not meant to be there.
> * Bandaid text seems to suggest that you can regenerate your health, which is partially true but it's not possible to regenerate wound levels. It might be more clear saying something like "you may regenerate small injuries but not wound levels".
> * Currently sounds like the invincibility is a permanent effect. Might be helpful to list the effects duration (5 seconds, for the current level, etc).

Thanks for the feedback.
- Managed to fix shop interface appearing in level 3
- Made sure feedback doesn't appear in different shop interfaces
- Fixed safehouse music being played in epilogue
- Coins quantity used to be randomize to be between 0 to 5. It will not be 1 to 5
- Fixed updating equipping player's melee weapon type when going from one level to the next
- Reloading is a little tricky because it takes 3 seconds for player to  finish reloading. It's easier to just fill up the number of bullets available for shooting to 5 again
- What do you mean if when buying items in the shop would update the sprite on the right side of the shop interface? I think i've made it such that coin and bandage number would update. You mean like an image of that item that was bought should be displayed as well? 
- Yes. That will most likely be done when polishing. There should be a box that will be displayed when an item is selected or something that clearly indicate which item has been clicked
- Updated description text for dash, bandage and invincibility.

Let me know what you think @DancingBrian !

**Comment by DancingBrian** [comment]
> 
> Thanks for the feedback.
> 
>     * Managed to fix shop interface appearing in level 3
> 
>     * Made sure feedback doesn't appear in different shop interfaces
> 
>     * Fixed safehouse music being played in epilogue
> 
>     * Coins quantity used to be randomize to be between 0 to 5. It will now be 1 to 5
> 
>     * Fixed updating equipping player's melee weapon type when going from one level to the next
> 
>     * Reloading is a little tricky because it takes 3 seconds for player to  finish reloading. It's easier to just fill up the number of bullets available for shooting to 5 again
> 
>     * What do you mean if when buying items in the shop would update the sprite on the right side of the shop interface? I think i've made it such that coin and bandage number would update. You mean like an image of that item that was bought should be displayed as well?
> 
>     * Yes. That will most likely be done when polishing. There should be a box that will be displayed when an item is selected or something that clearly indicate which item has been clicked
> 
>     * Updated description text for dash, bandage and invincibility.
> 
> 
> Let me know what you think @DancingBrian !

Nice, most of those issues are fixed now!

Yep, for the shop interface it would be nice to have the player wearing a helmet if they currently own one, or holding a dagger if that is what they currently have equipped (just to remind the user what items/abilities they currently have equipped).

For the weapon purchasing issue, it still occasionally lets the user buy the same weapon they have equipped. To replicate:
* On level 1 pick up a dagger (don't pick up any other weapon)
* Go back to the shop at the start of level one and purchase a dagger. This lets the user buy the weapon rather than display "already equipped".

For the rock issue, I thought I would expand a little as I probably wasn't very clear on the issue. When the rocks are refilled back up to 5 bullets available to shoot, the number of rocks in inventory would have to be reduced by the same amount, otherwise the player will get additional rocks each time they enter the safehouse. Don't know if that makes any sense... 
For an example:
* The total rocks the player has at the start of the game is 15 (5 ready to shoot and 10 in inventory)
* If the player then throws two rocks on level one but doesn't pick up any new rocks then they end the level with 13 rocks (3 ready to shoot and 10 in inventory)
* Currently when the player enters the safehouse the rocks ready to shoot will be refilled back up to 5 and therefore giving the player 2 extra rocks, in this case to have a total of 15 rocks again (5 ready to shoot and 10 in inventory), however they should only have 13 rocks.

**Comment by Bluehalomango** [comment]
> For the weapon purchasing issue, it still occasionally lets the user buy the same weapon they have equipped...

I suspect this is an unintended side effect due to being able to pick up a weapon in the same stage as buying one. As the ability to pickup weapons in a level is just a placeholder for testing purposes at the moment, this issue will be resolved once we remove the test weapon spawns. If it persists, we will look more into it but from my understanding, its due to how the saving system works.

> For the rock issue, I thought I would expand a little as I probably wasn't very clear on the issue...

Fix should be up shortly. The codes written, just not able to commit atm. When its up, the ammo count will adjust according to the surplus and magazine count at the end of a level.

**Comment by 25Ericcheong** [comment]
> > Thanks for the feedback.
> > ```
> > * Managed to fix shop interface appearing in level 3
> > 
> > * Made sure feedback doesn't appear in different shop interfaces
> > 
> > * Fixed safehouse music being played in epilogue
> > 
> > * Coins quantity used to be randomize to be between 0 to 5. It will now be 1 to 5
> > 
> > * Fixed updating equipping player's melee weapon type when going from one level to the next
> > 
> > * Reloading is a little tricky because it takes 3 seconds for player to  finish reloading. It's easier to just fill up the number of bullets available for shooting to 5 again
> > 
> > * What do you mean if when buying items in the shop would update the sprite on the right side of the shop interface? I think i've made it such that coin and bandage number would update. You mean like an image of that item that was bought should be displayed as well?
> > 
> > * Yes. That will most likely be done when polishing. There should be a box that will be displayed when an item is selected or something that clearly indicate which item has been clicked
> > 
> > * Updated description text for dash, bandage and invincibility.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Let me know what you think @DancingBrian !
> 
> Nice, most of those issues are fixed now!
> 
> Yep, for the shop interface it would be nice to have the player wearing a helmet if they currently own one, or holding a dagger if that is what they currently have equipped (just to remind the user what items/abilities they currently have equipped).
> 
> For the weapon purchasing issue, it still occasionally lets the user buy the same weapon they have equipped. To replicate:
> 
> * On level 1 pick up a dagger (don't pick up any other weapon)
> * Go back to the shop at the start of level one and purchase a dagger. This lets the user buy the weapon rather than display "already equipped".
> 
> For the rock issue, I thought I would expand a little as I probably wasn't very clear on the issue. When the rocks are refilled back up to 5 bullets available to shoot, the number of rocks in inventory would have to be reduced by the same amount, otherwise the player will get additional rocks each time they enter the safehouse. Don't know if that makes any sense...
> For an example:
> 
> * The total rocks the player has at the start of the game is 15 (5 ready to shoot and 10 in inventory)
> * If the player then throws two rocks on level one but doesn't pick up any new rocks then they end the level with 13 rocks (3 ready to shoot and 10 in inventory)
> * Currently when the player enters the safehouse the rocks ready to shoot will be refilled back up to 5 and therefore giving the player 2 extra rocks, in this case to have a total of 15 rocks again (5 ready to shoot and 10 in inventory), however they should only have 13 rocks.

Okay, managed to fix the issue where the rocks refill (player gets extra ammo). It should be tracked and not be refilled when player enter/leaves a safehouse and when player transitions from one level to another. 

Ah, I understand what you mean for the shop interface. I think this is doable - might be more of a polishing thing. But can be done I believe and as @Bluehalomango has mentioned, picking up weapons in level 1 was purely for testing and will be removed. 

Ideally, player can only get/use different weapons when they're in safehouse (by buying items from the shop). The player states are not being updated correctly when picking up cause I coded it that way but can be altered and improved to incorporate picking weapon up. If this is actually a thing and if we do decide to expand and allow players to pickup and use weapons [possibly in tutorial? But can be done if needed].

**Comment by DancingBrian** [comment]
> 
> 
> > > Thanks for the feedback.
> > > ```
> > > * Managed to fix shop interface appearing in level 3
> > > 
> > > * Made sure feedback doesn't appear in different shop interfaces
> > > 
> > > * Fixed safehouse music being played in epilogue
> > > 
> > > * Coins quantity used to be randomize to be between 0 to 5. It will now be 1 to 5
> > > 
> > > * Fixed updating equipping player's melee weapon type when going from one level to the next
> > > 
> > > * Reloading is a little tricky because it takes 3 seconds for player to  finish reloading. It's easier to just fill up the number of bullets available for shooting to 5 again
> > > 
> > > * What do you mean if when buying items in the shop would update the sprite on the right side of the shop interface? I think i've made it such that coin and bandage number would update. You mean like an image of that item that was bought should be displayed as well?
> > > 
> > > * Yes. That will most likely be done when polishing. There should be a box that will be displayed when an item is selected or something that clearly indicate which item has been clicked
> > > 
> > > * Updated description text for dash, bandage and invincibility.
> > > ```
> > > 
> > > 

> 
> Okay, managed to fix the issue where the rocks refill (player gets extra ammo). It should be tracked and not be refilled when player enter/leaves a safehouse and when player transitions from one level to another.
> 
> Ah, I understand what you mean for the shop interface. I think this is doable - might be more of a polishing thing. But can be done I believe and as @Bluehalomango has mentioned, picking up weapons in level 1 was purely for testing and will be removed.
> 
> Ideally, player can only get/use different weapons when they're in safehouse (by buying items from the shop). The player states are not being updated correctly when picking up cause I coded it that way but can be altered and improved to incorporate picking weapon up. If this is actually a thing and if we do decide to expand and allow players to pickup and use weapons [possibly in tutorial? But can be done if needed].

Yeah I think the shop interface thing is a "nice to have", so sprint 4 might make more sense. The number of rocks in the safehouse is working well for me now :)

**Pull request merged**
