### PR TITLE
S2 t2 feature/player - Final Merge Additions

### PR DESCRIPTION
**Pull request by Bluehalomango**
Last major commit for player/item feature of sprint 2:
- Added in 2 more weapons (dagger and axe) with their own stats and animations
- Added a duration and attack length to melee attacks (i.e. you can't spam attack anymore)
- Added in armour and armour animations that effect player defence (Note, player no longer has hurt animation once they have armour)
- Added the weapons, armour and various items as things the player can pickup ingame. Currently, this is for testing purposes and and will be changed when there are more appropriate means of collection (i.e. safehouse store, enemies dropping items, etc.)
- Added in multiple coin sprites (single, stack and bag of coins)
- Finalised player HUD
- Changed dashbar to be for the player's special ability
- Changed some stuff with how disposing works
- Tried to clean up and reduce complexity of several classes
- Added in the local gameArea as a globally accessible service in ServiceLocator to allow entities to be despawned properly. Gets changed each level transition as well.
- A lot more testing of everything

There might an additional ability coming in last today, not sure yet but will update this if it ends up including it.

### CODE REVIEW

**Comment by kainphoton** [comment]
The weapons work well with good hitbox and attack length.  I'll assume the weapon and the armor not carrying over the safehouse and next level is intentional.  Good job with fixing the door bug for the safehouse.  The only minor problem I see is that every now and then, the game crashes when the player dies and it shows this message

image

**Comment by Bluehalomango** [comment]
> The weapons work well with good hitbox and attack length. I'll assume the weapon and the armor not carrying over the safehouse and next level is intentional. Good job with fixing the door bug for the safehouse. The only minor problem I see is that every now and then, the game crashes when the player dies and it shows this message
> 
> image

Haven't seen that issue before, I'll try looking into it. And yeah, things won't carry over until a save system or something similar is implemented in a later sprint.

**Comment by Bluehalomango** [comment]
> 
> image
Should be fixed now.

**Comment by kainphoton** [comment]
> > image
> > Should be fixed now.

lgtm, I can't replicate that bug anymore, nice job.

**Pull request merged**
