### PR TITLE
S1 t2 feature/player

### PR DESCRIPTION
**Pull request by 25Ericcheong**
Summary:
- includes files for player and projectile sprites
- bullets can now be spawned in game world (relevant entity and components created along it)
- player has the ability to dash
- player's health can now regenerate during the game after a period of time
- disposing component (DisposingComponent.java) can be used to dispose of any entity in game now as long as it is attached to an entity
- player's long range attack (can be launched in 4 directions based on player's movement)
- disabled atlas.dispose() in AnimationRenderCcomponent.java [this gets rid of an entire animation instance of all entities with similar animation]
- player's appearance uses sprite (temporary currently, can be changed)

Issues related:
- #41 
- #36 
- #27 
- #20 

Wiki related:
- https://github.com/UQdeco2800/2021-studio-6/wiki/Player-Overview-Description

### CODE REVIEW

**Comment by DancingBrian** [comment]
These new features are working well on my end. Projectile functionality seems clear and intuitive. The dash currently feels more like a teleport so could considering displaying the sprite moving quickly in future sprints, but other than that the Dash functionality worked seamlessly. As there are no merge conflicts then there shouldn't be any issues merging.

**Review by DancingBrian — APPROVED** [review]
These new features are working well on my end. Projectile functionality seems clear and intuitive. The dash currently feels more like a teleport so could considering displaying the sprite moving quickly in future sprints, but other than that the Dash functionality worked seamlessly. As there are no merge conflicts then there shouldn't be any issues merging. 

Small note: The game music seems to have been disabled with this pull request, not sure if this was intentional

**Comment by 25Ericcheong** [comment]
> These new features are working well on my end. Projectile functionality seems clear and intuitive. The dash currently feels more like a teleport so could considering displaying the sprite moving quickly in future sprints, but other than that the Dash functionality worked seamlessly. As there are no merge conflicts then there shouldn't be any issues merging.
> 
> Small note: The game music seems to have been disabled with this pull request, not sure if this was intentional

Yes, I've enabled debugging (so you can see the fixture boxes) and disabled music. I can reactivate music and disable debugging if you want. Let me know.

**Comment by DancingBrian** [comment]
> 
> 
> > These new features are working well on my end. Projectile functionality seems clear and intuitive. The dash currently feels more like a teleport so could considering displaying the sprite moving quickly in future sprints, but other than that the Dash functionality worked seamlessly. As there are no merge conflicts then there shouldn't be any issues merging.
> > Small note: The game music seems to have been disabled with this pull request, not sure if this was intentional
> 
> Yes, I've enabled debugging (so you can see the fixture boxes) and disabled music. I can reactivate music and disable debugging if you want. Let me know.

Nope all good, was just checking that disabling the music was intentional

**Pull request merged**
