### PR TITLE
S2 t2 feature/player - First Batch of Additions

### PR DESCRIPTION
**Pull request by Bluehalomango**
First Major Batch of player additions. Currently, most item stuff is still being worked on so this is mainly for the player.
- Changed PlayerMeleeAttackComponent to be variable-based. That is, it can be passed a config file that will set the attack parameters.
- Change the melee attack to be directional based instead of just all around the player. Now the player will only attack in the last direction they moved/faced.
- Added interface animations for player health and dash. Currently, this will only show up once the player gets hurt or dashes to get around an issue in loading and rendering order at game start. There is a placeholder health bar in until hit as well.
- Numerical health bars are still in atm for testing purposes
- Created and added a new class, IndependentAnimator, that can be used to animate something without being attached to an entity. Currently draws animation based on overall position of camera (i.e. moves with the player).
- Added limited ammo and reload to the player's ranged attack. Can only shot a certain amount before running out.
- Added a PlayerAbility triggering system
- Added a 'Long Dash' special ability to 'E' that goes on a long cooldown after use
- Added an InventoryDisplay component for later use with items
- Changed dialogue advance key to M due to conflict with attack triggering
- Disabled player attacks in safehouse to deal with some bugs
- (also added a lot of tests for previously added/new classes)

### CODE REVIEW

**Comment by DancingBrian** [comment]
Having a couple of issues at the moment but not sure if it is just me:
- On about 1 in 4 restarts I get an game exiting error (shown below)
- The HUD health bar starts small but then when the player gets hit it gets bigger
- Sprint cooldown bar is not displayed until clicking sprint for the first time
- If I sprint in the safehouse then the attacks/shooting ability is enabled again

image

**Comment by DancingBrian** [comment]
Other feedback so far:
- The long dash seems to be working well, will this be possibly recharged through items? (as I couldn't seem to recharge it)
- I like the really slow health recovery, it already makes the game feel more scarier (trying to hide while recovering health). 
- Sprint bar was working well, I found it very useful
- The directional combat makes much more sense, and was working on my end. Limiting shooting to 5 bullets also worked well.

**Comment by Bluehalomango** [comment]
> Having a couple of issues at the moment but not sure if it is just me:
> 
> * On about 1 in 4 restarts I get an game exiting error (shown below)
> * The HUD health bar starts small but then when the player gets hit it gets bigger
> * Sprint cooldown bar is not displayed until clicking sprint for the first time
> * If I sprint in the safehouse then the attacks/shooting ability is enabled again
> 

I believe the first issue is due to getting hit by enemies while loading into the game or something to that affect. The health bar being small is a temporay placeholder as outlined in the merge description, due to the same reason that the dashbar does not show up until dashing. These all come from the same issue; that is, trying to animate assets before everything has loaded. I have been trying to find somewhere in the code at which point everything will have loaded by but I have yet to find it. I was hoping to talk to either Team 3 or 5 about it tommorow but I will try to resolve it before then.

That last issue we have not encountered yet and will try to resolve it.

**Comment by DancingBrian** [comment]
> 
> 
> > Having a couple of issues at the moment but not sure if it is just me:
> > 
> > * On about 1 in 4 restarts I get an game exiting error (shown below)
> > * The HUD health bar starts small but then when the player gets hit it gets bigger
> > * Sprint cooldown bar is not displayed until clicking sprint for the first time
> > * If I sprint in the safehouse then the attacks/shooting ability is enabled again
> 
> I believe the first issue is due to getting hit by enemies while loading into the game or something to that affect. The health bar being small is a temporay placeholder as outlined in the merge description, due to the same reason that the dashbar does not show up until dashing. These all come from the same issue; that is, trying to animate assets before everything has loaded. I have been trying to find somewhere in the code at which point everything will have loaded by but I have yet to find it. I was hoping to talk to either Team 3 or 5 about it tommorow but I will try to resolve it before then.
> 
> That last issue we have not encountered yet and will try to resolve it.

Ah yes, I see you have a line in there about the health/sprint bar, apologies for missing that. If the game crash at the start isn't fixable at this stage then I think you should be good to merge.

**Review by DancingBrian — APPROVED** [review]

**Comment by Bluehalomango** [comment]
> 
> Ah yes, I see you have a line in there about the health/sprint bar, apologies for missing that. If the game crash at the start isn't fixable at this stage then I think you should be good to merge.

I think I've managed to fix the all the issues you pointed out and have removed the temp health bar as well as it is no longer needed.

**Comment by DancingBrian** [comment]
> 
> 
> > Ah yes, I see you have a line in there about the health/sprint bar, apologies for missing that. If the game crash at the start isn't fixable at this stage then I think you should be good to merge.
> 
> I think I've managed to fix the all the issues you pointed out and have removed the temp health bar as well as it is no longer needed.

Nice! Yep from my end everything looks like it is working. The temp health bar was still appearing for me when the game loads but it dissapears once the player is hit for the first time.

**Comment by Bluehalomango** [comment]
> Nice! Yep from my end everything looks like it is working. The temp health bar was still appearing for me when the game loads but it dissapears once the player is hit for the first time.

Just went and fixed that up.

**Pull request merged**
