### PR TITLE
S3 t3 feature/darkness, expanded lighting Components

### PR DESCRIPTION
**Pull request by yourlow**
Added new lights to play with 

- conelight 
- chainlight
- directionlight (couldn't get this to work well but its in there)

These are documented with examples on the [wiki](https://github.com/UQdeco2800/2021-studio-6/wiki/Lighting-Engine)

also updated comments and logging so hopefully there a bit easier to use!

### CODE REVIEW

**Comment by DancingBrian** [comment]
Looks good! The cone version is going to be so good for the torch item, although I couldn't seem to get the offset or direction degree to change the light positioning/direction. Are you able to send through an example code for one where the torch is facing a different direction?
These two direction degrees didn't seem to change anything for me:
`
.addComponent(new ConeLightComponent(Colors.get("RED"), 10f, 1f, 1f, 180f, 45f));
`
`
.addComponent(new ConeLightComponent(Colors.get("RED"), 10f, 1f, 1f, 0.5f, 45f));
`

**Comment by yourlow** [comment]
good catch, when i was debugging i put some test code in there to rotate the light so it always rotated 180 degrees, ill update it so it works properly

**Comment by yourlow** [comment]
So you currently can't add multiple of the same component to a single entity, It seems like a legit use caseto want multiple lights on a single component, what use case were you thinking of cause i might add a check in Entity.java so an entity can have multiple lights

**Comment by yourlow** [comment]
rotation + offset issues should be fixed in the latest commits

**Comment by DancingBrian** [comment]
> 
> 
> rotation + offset issues should be fixed in the latest commits

Nice, yep that seems to be working now! The example before were just two different values I was testing for the rotation degrees parameter, however I was just adding the one lighting component to the entity at any one time. Not sure if we would need two lighting components on the one entity, guess that might be a question for the player team.

**Review by DancingBrian — APPROVED** [review]

**Pull request merged**
