### PR TITLE
S1T5-Feature/Level

### PR DESCRIPTION
**Pull request by Lumin-cider**
### Summary
- New Areas are added, this is served as the "levels" in the game, in-between each level, a safehouse game area is implemented, where player can rest and purchase items (next sprint).
- New functions are added to the game, this includes pause/resume, camera movement and game area transition. When players complete a game area and touches the safehouse, they will be transported to the inside of the safehouse. Inside the safehouse is a new entity, door, similar to safehouse, it will transport player out of the safehouse and into the next level.
- The pause screen displayed when you hit the `ESCAPE` key, the pause display is a placeholder so the continue button doesn't work.  **Some problems with the pause screen are:** 
  - Not resizable when you change the window screen
  - Minimizing the GdxGame screen will put the pause screen in the bottom left corner
  - Not freeze the player walking animation
  - These bugs are to be fixed/updated in the future sprints.  Basically just wanted to get the pause functionality working somewhat
- At the moment the game exits to main menu after the player transitions through Level 3's safehouse.

### Files added
`Level2.java`- represents Level 2 of the game
`Level3.java` - represents Level 3 of the game
`Safehouse.java` - the interior of the safehouse
`SafehouseFactory.java` - a factory to create the safehouse entity

### Files changed
`ForestGameArea.java` - added new spawning methods for new entities
`MainGameScreen.java` - added methods for auto-changing between levels when player collide with the safehouse and also adding codes to allow camera movement
`MainGameExitDisplay.java` - added a window component for displaying the pause display when game is paused, this should really be in its own component like MainGamePauseDisplay for example (todo for future sprints)
`KeyboardPlayerInputComponent.java` - added the `ESCAPE` key functionality to freeze the player's action, may need to change this in later sprints

### Feature/Tasks
- #7 
- #33 
- #34 
- #32 
- #35

### Documentation
[Safehouse Wiki](https://github.com/UQdeco2800/2021-studio-6/wiki/Safehouse-Overview)

### CODE REVIEW

**Comment by kainphoton** [comment]
Currently updating the code to suit with Team 3's merge to main branch

**Comment by kainphoton** [comment]
Movement wise, the game mostly works, can transition through the safehouse and other levels.  But once you start attacking with projectiles, **multiple bugs can happen** such as:

- Player zooming across the map, seems to happen when you make contact with the safehouse, this bug will actually stick until you gradlew run it again...
- Projectiles not unloading properly in safehouse area, after travelling certain distance, it just stays there
- Game crashes randomly probably due to not unloading assets properly through game area transition

I know this commit is questionable to merge into the main branch but we just want to submit something for sprint 1 🤕, so you guys can always just revert or fix the commits on the main branch for the next sprint.

**Review by Bluehalomango — COMMENTED** [review]
It'll be hard to merge with the amount of bugs you seem to be having but I suspect that most of those bugs will require the help and work of the other teams to properly integrate together so it may be a case of having to merge in order to fix the bugs. I know the projecticles work in a specific way so our team would probably have to look at how things are setup in order to fix that issue at least. I think the game crashing though is a bit of a problem but it sounds like you'll have to merge anyway.

**Comment by kainphoton** [comment]
Yeah sorry, we didn't really want to merge into the main branch but we have to submit something for the Sprint 1 assessment.

**Pull request merged**
