### PR TITLE
S2 T1 feature/story

### PR DESCRIPTION
**Pull request by DancingBrian**
The followings features have been added in this pull request. Would love to hear any feedback/ideas.

# General changes
- Pause mechanics have been reworked and can now be activated through the Game Time class by calling the pause and unpause methods
- Keyboard input related to the main game screen has been separated out of the KeyboardPlayerInputComponent class and into a new class KeyboardLevelInputComponent
- The pause menu can now be toggled by triggering the "togglepause" event.
- When the player is dead a new event is triggered called "dead".
- Minor changes to main menu and settings screens

# Story manager
- New classes have been created for the story manager in preparation for the prologue and epilogue scenes later in the sprint.
- Related ticket: #73 

# Pause Menu
- Pause menu screen has been updated when the player hits the escape button from the main game screen
- The pause menu design is temporary and will hopefully be updated before the end of the sprint
- Pause menu screen has the following functionality
   - Continue button - unpauses the game and removes the pause menu
   - Settings button - displays the game settings (note the game settings have not been updated at this stage)
   - Exit to menu button - takes the user back to the main menu by calling the main menu screen
   - Exit game button - exits the application
- Related ticket: #77 

image
  
# Game Over Screen
- Game over screen will now appear when the player is dead
- When the player is dead the game is paused for a short time before the game over screen is displayed. This is so that a death animation and sound effect can be played before switching screens. Note that the animation and sound effects will most likely not be implemented in this sprint.
- The game over screen design is temporary and will hopefully be updated before the end of the sprint
- Game over screen has the following functionality
   - Restart game button - restarts the game from the start by calling the main game screen
   - Return to menu button - takes the user back to the main menu by calling the main menu screen
   - Exit button - exits the application
- Related ticket: #76 

image

### CODE REVIEW

**Review by Bluehalomango — APPROVED** [review]
Looks all good. Smart idea to split up KeyboardInput, the complexity of it has slowly been getting worse and worse as we add new stuff... At least now its divided in a way that makes sense.

**Comment by 25Ericcheong** [comment]
Everything is working on my end. Can't wait to have sound effect when player dies later in the semester. Is `ImageSequence.java` related to the prologue and epilogue scenes as well? Just wondering. Also, it seems like having a game over screen kind of solved this issue #53. Great work guys!

**Review by 25Ericcheong — APPROVED** [review]
Everything is working on my end. Can't wait to have sound effect when player dies later in the semester. Is ImageSequence.java related to the prologue and epilogue scenes as well? Just wondering. Also, it seems like having a game over screen kind of solved this issue #53. Great work guys!

**Comment by DancingBrian** [comment]
> 
> 
> Everything is working on my end. Can't wait to have sound effect when player dies later in the semester. Is ImageSequence.java related to the prologue and epilogue scenes as well? Just wondering. Also, it seems like having a game over screen kind of solved this issue #53. Great work guys!

Thanks Ericcheong! Yes the ImageSequence class is related to the prologue/epilogue scenes, it is one of the classes to set the framework for when the scenes have been designed. For #53 , the issue is being hidden at the moment due to the game pausing when the player dies... so the bug will probably appear again in different places (like the safehouse random teleport in bug if a projectile hits it).

**Pull request merged**
