### PR TITLE
S1 - T5 feature/enemies

### PR DESCRIPTION
**Pull request by yourlow**
Enemies Feature, _at a glance_

3 enemies added: `Long Range`, `Small enemy`, `Large enemy`

files added:

`BulletFactory`: for creating bullets
`BulletCollider`: collider component for bullets
`DistanceFireBulletTask`: ai task 'fire bullet at enemy within a certain radius'
`FireBulletTask`: simpler implementation of `DistanceFireBulletTask` 
`FireBulletListener`: component for listening to the ai `FireBulletTask`'s

files Changed:

`NPCFactory`: Extensive changes, added factories for the 3 enemies
`ForestGameArea`: added spawning functions for the 3 enemies
`TextureRenderComponent`: changed `draw` function to add rotation capability to texture components

`PhysicsEngine`: changed how physics bodies are being destroyed (the game will crash without this)
`ColliderComponent` add to comment out the destruction of fixtures
For reasoning behind these last two changes refer to this issue on the game engine https://github.com/UQdeco2800/game-engine/issues/8

also added all assets for the enemies

note: going to keep T5 but it really should be T3, you can blame @yourlow for this tragedy

### CODE REVIEW

**Review by Bluehalomango — COMMENTED** [review]
Uhh, this merge adds and changes a fair bit of stuff... Do you mind adding a description to your request to go over the main stuff, particularly what you've changed with other files? Otherwise it'll be tricky to check everything.

**Comment by 25Ericcheong** [comment]
Might be worth pulling main into your feature branch first and solving the conflicts locally before creating a pull request I believe. Just had a look at your commits, main hasn't been merged into your feature branch since we started working on the project.

**Comment by DancingBrian** [comment]
Enemies seem to work well, I like that they all look distinct so that it is easy to tell them apart.  As other comments have mentioned: should add a description and fix merge conflicts before merging the pull request.

**Review by Bluehalomango — APPROVED** [review]
Looks pretty good. Seem to have a few inconsistencies with formating and styling (i.e. a bunch of the files changed just seem to be from identation) but its hard to tell how that looks here. Should be fine though.

**Comment by yourlow** [comment]
There's some quite bad breaking changes with the current main branch going (mainly our interactions with the player) going to fix them in this merge!

**Pull request merged**
