### PR TITLE
S1 - T2 Player Final Changes

### PR DESCRIPTION
**Pull request by Bluehalomango**
Last merge for player features, includes:

- Player Dash overhaul + testing
- Directional player animations (currently very simplistic, to be refined in later sprints)
- Additional refinement and testing of dispose component
- Player component gets disposed on death
- Overall code cleanup and testing

### CODE REVIEW

**Comment by kainphoton** [comment]
Player dashing looks smooth and good on my end. The player death works.  Directional player animations works well. Nice job!

**Comment by DancingBrian** [comment]
Sprint and the animations for each direction look great! Player disappeared successfully for me when the player died. When testing I wasn't able to shoot anymore, was this functionality removed (e.g. can only shoot if we pick up a gun)? There was also a bullet sprite in the bottom left corner (see image below) but it probably wouldn't display for most screen resolutions.

image

**Comment by Bluehalomango** [comment]
> Sprint and the animations for each direction look great! Player disappeared successfully for me when the player died. When testing I wasn't able to shoot anymore, was this functionality removed (e.g. can only shoot if we pick up a gun)? There was also a bullet sprite in the bottom left corner (see image below) but it probably wouldn't display for most screen resolutions.
> 
> image

The attack keybinding was changed to Enter so that was probably the problem. Not sure whats the go with the sprite, nobody else on our team has seen that. What resolution are you playing on? That might be the issue.

**Comment by DancingBrian** [comment]
> 
> 
> > Sprint and the animations for each direction look great! Player disappeared successfully for me when the player died. When testing I wasn't able to shoot anymore, was this functionality removed (e.g. can only shoot if we pick up a gun)? There was also a bullet sprite in the bottom left corner (see image below) but it probably wouldn't display for most screen resolutions.
> 
> 
> The attack keybinding was changed to Enter so that was probably the problem. Not sure whats the go with the sprite, nobody else on our team has seen that. What resolution are you playing on? That might be the issue.

Ah yes enter works, projectiles are still working then :)
Resolution of my screen is 1920x1080 but I have it snapped to the side (to display two windows at once) so it only takes up half of that. So resolution of the game would be 960x1080.

**Review by DancingBrian — APPROVED** [review]

**Comment by 25Ericcheong** [comment]
> > > Sprint and the animations for each direction look great! Player disappeared successfully for me when the player died. When testing I wasn't able to shoot anymore, was this functionality removed (e.g. can only shoot if we pick up a gun)? There was also a bullet sprite in the bottom left corner (see image below) but it probably wouldn't display for most screen resolutions.
> > 
> > 
> > The attack keybinding was changed to Enter so that was probably the problem. Not sure whats the go with the sprite, nobody else on our team has seen that. What resolution are you playing on? That might be the issue.
> 
> Ah yes enter works, projectiles are still working then :)
> Resolution of my screen is 1920x1080 but I have it snapped to the side (to display two windows at once), so it only takes up half of that. So resolution of the game would be 960x1080.

Hey, just wanted to let you know. This is how bullets are being produced in the game and I've hidden them on the game screen (and it can clearly be seen by you but I've changed it so that it is even more hidden now. It's been pushed to main but let me know if you could still see the bullets)

**Pull request merged**
