### PR TITLE
Main bug solving

### PR DESCRIPTION
**Pull request by 25Ericcheong**
A bug mentioned in #160 . This should solve it. Let me know if this solves it.

### CODE REVIEW

**Comment by DancingBrian** [comment]
Looks like it partially fixed it. 

This is now working correctly:
- Pause the game
- Press the 'w' key down 
- Release the 'w' key
- Unpause, and the the issue doesn't occur.

The issue still occurs if you don't release the button:
- Pause the game
- Press the 'w' key down 
- Unpause
- Release the 'w' key, and the player will continuously walk in the 's' direction.

Not sure if it helps, but each time you activate the bug (by pausing, moving, unpausing), the players speed gets faster, to the point where you can run through the first level in a couple of seconds.

Let me know if you are unable to replicate the issue and I will screen capture and send through a video.

**Comment by 25Ericcheong** [comment]
> Looks like it partially fixed it.
> 
> This is now working correctly:
> 
> * Pause the game
> * Press the 'w' key down
> * Release the 'w' key
> * Unpause, and the the issue doesn't occur.
> 
> The issue still occurs if you don't release the button:
> 
> * Pause the game
> * Press the 'w' key down
> * Unpause
> * Release the 'w' key, and the player will continuously walk in the 's' direction.
> 
> Not sure if it helps, but each time you activate the bug (by pausing, moving, unpausing), the players speed gets faster, to the point where you can run through the first level in a couple of seconds.
> 
> Edit: Readded a sentence as the player still speeds up with the new fix
> 
> Let me know if you are unable to replicate the issue and I will screen capture and send through a video.

Ye. Managed to fabricate it. It was a very weird bug. I think it was something that existed even in the base of the game. We just never realized it till now. The same bug will happen if you repeat the entire process during the prologue too. I think its because the code was implemented in such a way that it assumes `keyDown` would always occur first then `keyUp` would happen after. But you've managed to execute `keyUp` first which didn't follow that particular rule - but I've managed to get rid of it - let me know if the bug is still there.

**Comment by DancingBrian** [comment]
> 
> Ye. Managed to fabricate it. It was a very weird bug. I think it was something that existed even in the base of the game. We just never realized it till now. The same bug will happen if you repeat the entire process during the prologue too. I think its because the code was implemented in such a way that it assumes `keyDown` would always occur first then `keyUp` would happen after. But you've managed to execute `keyUp` first which didn't follow that particular rule - but I've managed to get rid of it - let me know if the bug is still there.

Ah nice, that seemed to fix the issue! Although now a possible related issue is occuring where:
- Hold 'w' key down
- Pause the game
- Release the 'w' key while on pause menu
- Unpause the game, and the character will continue running in that direction.

It sounds like it could be a similar issue where the walk command is waiting for a keyup, however the keyup is occurring while the game is paused.

**Comment by 25Ericcheong** [comment]
> > Ye. Managed to fabricate it. It was a very weird bug. I think it was something that existed even in the base of the game. We just never realized it till now. The same bug will happen if you repeat the entire process during the prologue too. I think its because the code was implemented in such a way that it assumes `keyDown` would always occur first then `keyUp` would happen after. But you've managed to execute `keyUp` first which didn't follow that particular rule - but I've managed to get rid of it - let me know if the bug is still there.
> 
> Ah nice, that seemed to fix the issue! Although now a possible related issue is occuring where:
> 
> * Hold 'w' key down
> * Pause the game
> * Release the 'w' key while on pause menu
> * Unpause the game, and the character will continue running in that direction.
> 
> It sounds like it could be a similar issue where the walk command is waiting for a keyup, however the keyup is occurring while the game is paused.

Yeah. I realized this could've been an issue right after pushing. Ok, i'm quite certain there shouldn't be any more bugs related pausing + moving. Player needs to have ESC key occupied as well just to reset all checking conditions. Note that player still moves a little even after pausing (the most recent issue you mentioned) but I can't really find a solution to that tbh.

**Comment by DancingBrian** [comment]
> 
> 
> > > Ye. Managed to fabricate it. It was a very weird bug. I think it was something that existed even in the base of the game. We just never realized it till now. The same bug will happen if you repeat the entire process during the prologue too. I think its because the code was implemented in such a way that it assumes `keyDown` would always occur first then `keyUp` would happen after. But you've managed to execute `keyUp` first which didn't follow that particular rule - but I've managed to get rid of it - let me know if the bug is still there.
> > 
> > 
> > Ah nice, that seemed to fix the issue! Although now a possible related issue is occuring where:
> > 
> > * Hold 'w' key down
> > * Pause the game
> > * Release the 'w' key while on pause menu
> > * Unpause the game, and the character will continue running in that direction.
> > 
> > It sounds like it could be a similar issue where the walk command is waiting for a keyup, however the keyup is occurring while the game is paused.
> 
> Yeah. I realized this could've been an issue right after pushing. Ok, i'm quite certain there shouldn't be any more bugs related pausing + moving. Player needs to have ESC key occupied as well just to reset all checking conditions. Note that player still moves a little even after pausing (the most recent issue you mentioned) but I can't really find a solution to that tbh. Let me know if its ok on your machine.

It is working now for when the user presses the ESC key to unpause, however if the user clicks the continue button then the issue still occurs. As we will be pausing the game for NPC dialogue as well, would it be possible to make the reset positions publicly callable? If so, then we could call it every time the game is paused/unpaused.

**Comment by 25Ericcheong** [comment]
> > > > Ye. Managed to fabricate it. It was a very weird bug. I think it was something that existed even in the base of the game. We just never realized it till now. The same bug will happen if you repeat the entire process during the prologue too. I think its because the code was implemented in such a way that it assumes `keyDown` would always occur first then `keyUp` would happen after. But you've managed to execute `keyUp` first which didn't follow that particular rule - but I've managed to get rid of it - let me know if the bug is still there.
> > > 
> > > 
> > > Ah nice, that seemed to fix the issue! Although now a possible related issue is occuring where:
> > > 
> > > * Hold 'w' key down
> > > * Pause the game
> > > * Release the 'w' key while on pause menu
> > > * Unpause the game, and the character will continue running in that direction.
> > > 
> > > It sounds like it could be a similar issue where the walk command is waiting for a keyup, however the keyup is occurring while the game is paused.
> > 
> > 
> > Yeah. I realized this could've been an issue right after pushing. Ok, i'm quite certain there shouldn't be any more bugs related pausing + moving. Player needs to have ESC key occupied as well just to reset all checking conditions. Note that player still moves a little even after pausing (the most recent issue you mentioned) but I can't really find a solution to that tbh. Let me know if its ok on your machine.
> 
> It is working now for when the user presses the ESC key to unpause, however if the user clicks the continue button then the issue still occurs. As we will be pausing the game for NPC dialogue as well, would it be possible to make the reset positions publicly callable? If so, then we could call it every time the game is paused/unpaused.

Yes. Very good point. My apologies, yes there is a way. And I've made sure that whenever toggle pause event is called (how game is being paused when pause screen is created or when dialogue is called), player's movement will reset as well. This should be a permanent fix now. I've tested all cases you've mentioned previously. Let me know if there's anything left.

**Comment by DancingBrian** [comment]
> 
> 
> > > > > Ye. Managed to fabricate it. It was a very weird bug. I think it was something that existed even in the base of the game. We just never realized it till now. The same bug will happen if you repeat the entire process during the prologue too. I think its because the code was implemented in such a way that it assumes `keyDown` would always occur first then `keyUp` would happen after. But you've managed to execute `keyUp` first which didn't follow that particular rule - but I've managed to get rid of it - let me know if the bug is still there.
> > > > 
> > > > 
> > > > Ah nice, that seemed to fix the issue! Although now a possible related issue is occuring where:
> > > > 
> > > > * Hold 'w' key down
> > > > * Pause the game
> > > > * Release the 'w' key while on pause menu
> > > > * Unpause the game, and the character will continue running in that direction.
> > > > 
> > > > It sounds like it could be a similar issue where the walk command is waiting for a keyup, however the keyup is occurring while the game is paused.
> > > 
> > > 
> > > Yeah. I realized this could've been an issue right after pushing. Ok, i'm quite certain there shouldn't be any more bugs related pausing + moving. Player needs to have ESC key occupied as well just to reset all checking conditions. Note that player still moves a little even after pausing (the most recent issue you mentioned) but I can't really find a solution to that tbh. Let me know if its ok on your machine.
> > 
> > 
> > It is working now for when the user presses the ESC key to unpause, however if the user clicks the continue button then the issue still occurs. As we will be pausing the game for NPC dialogue as well, would it be possible to make the reset positions publicly callable? If so, then we could call it every time the game is paused/unpaused.
> 
> Yes. Very good point. My apologies, yes there is a way. And I've made sure that whenever toggle pause event is called (how game is being paused when pause screen is created or when dialogue is called), player's movement will reset as well. This should be a permanent fix now. I've tested all cases you've mentioned previously. Let me know if there's anything left.
> Edit - if you need to call the reset condition - this will be it: `ServiceLocator.getGameArea().player.getEvents().trigger("resetPlayerMovements")`

Nice! Yep that seems to be working well now :)

Thanks for looking into it!

**Review by DancingBrian — APPROVED** [review]

**Pull request merged**
